[build]
builder = "nixpacks"
buildCommand = "NODE_ENV=production npm install --no-cache && npm run build"

[deploy]
startCommand = "npx serve dist"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "80"
VITE_API_URL = "https://billybobai-production.up.railway.app"
NODE_ENV = "production"