[build]
builder = "nixpacks"
buildCommand = ""

[deploy]
startCommand = "gunicorn app:app --workers 4 --threads 2 --timeout 120 --access-logfile - --error-logfile - --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"

[deploy.railway]
name = "billybobai"
root = "/backend"
