"""Update model relationships and remove duplicates

Revision ID: 00aba09dab33
Revises: b3f968e1959d
Create Date: 2025-04-14 10:40:10.645631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00aba09dab33'
down_revision: Union[str, None] = 'b3f968e1959d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'settings')
    op.alter_column('workflows', 'business_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=255),
               nullable=True)
    op.drop_constraint('workflows_user_id_fkey', 'workflows', type_='foreignkey')
    op.create_foreign_key(None, 'workflows', 'businesses', ['business_id'], ['id'])
    op.drop_column('workflows', 'user_id')
    op.drop_column('workflows', 'config')
    op.drop_column('workflows', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('workflows', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.create_foreign_key('workflows_user_id_fkey', 'workflows', 'users', ['user_id'], ['id'])
    op.alter_column('workflows', 'business_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=36),
               nullable=False)
    op.add_column('businesses', sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
